### Import library

In [1]:
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt

### `TransferFunction`
$$G(s)=\dfrac {s^4+2s^3+12s^2+7s+6}{s^3+9s^2+12s+8}$$

In [2]:
sys=signal.TransferFunction([1,2,12,7,6],[1,9,13,8])
sys

TransferFunctionContinuous(
array([ 1.,  2., 12.,  7.,  6.]),
array([ 1.,  9., 13.,  8.]),
dt: None
)

### `StateSpace`

In [3]:
A=np.array([[-3., -4.],
           [ 1.,  0.]])
B=np.array([[5.],
            [0.]])
C=np.array([[1., 6.]])
D=np.array([[0.0]])
sys=signal.lti(A,B,C,D)
sys

StateSpaceContinuous(
array([[-3., -4.],
       [ 1.,  0.]]),
array([[5.],
       [0.]]),
array([[1., 6.]]),
array([[0.]]),
dt: None
)

### `ZerosPolesGain`

In [4]:
signal.ZerosPolesGain([1, 2], [3, 4], 5)

ZerosPolesGainContinuous(
array([1, 2]),
array([3, 4]),
5,
dt: None
)

### Convert TransferFuncton to StateSpace

In [5]:
sys=signal.TransferFunction([1,6],[1,5,6])
ss=signal.StateSpace(sys)
ss

StateSpaceContinuous(
array([[-5., -6.],
       [ 1.,  0.]]),
array([[1.],
       [0.]]),
array([[1., 6.]]),
array([[0.]]),
dt: None
)

### Convert StateSpace to PolesZerosGain

In [6]:
zpk=signal.ZerosPolesGain(ss)
zpk

C:\Users\HP-NPC\anaconda3\lib\site-packages\scipy\signal\filter_design.py:1625: BadCoefficients: Badly conditioned filter coefficients (numerator): the results may be meaningless
  warnings.warn("Badly conditioned filter coefficients (numerator): the "


ZerosPolesGainContinuous(
array([-6.]),
array([-3., -2.]),
1.0000000000000018,
dt: None
)

So the system is $\dfrac{s+6}{(s+3)(s+2)}$

### `signal.lti()`

In [7]:
sys=signal.lti([1,2,12,7,6],[1,9,13,8])
sys

TransferFunctionContinuous(
array([ 1.,  2., 12.,  7.,  6.]),
array([ 1.,  9., 13.,  8.]),
dt: None
)

In [8]:
A=np.array([[-5., -6.],
           [ 1.,  0.]])
B=np.array([[1.],
            [0.]])
C=np.array([[1., 6.]])
D=np.array([[0.0]])
sys=signal.lti(A,B,C,D)
sys

StateSpaceContinuous(
array([[-5., -6.],
       [ 1.,  0.]]),
array([[1.],
       [0.]]),
array([[1., 6.]]),
array([[0.]]),
dt: None
)

In [9]:
signal.lti([1, 2], [3, 4], 5)

ZerosPolesGainContinuous(
array([1, 2]),
array([3, 4]),
5,
dt: None
)

### Partial fraction expansion

$$G(s)=\dfrac {7}{s^2+5s+6}$$

In [10]:
signal.residue([7],[1,5,6])

(array([ 7., -7.]), array([-2., -3.]), array([], dtype=float64))

$$G(s)=\dfrac {7}{s^2+5s+6}=\dfrac {7}{s+2}+\dfrac {-7}{s+3}$$

In [11]:
signal.residue([1,-4,3],[1,4,3,0])
#distinct pole

(array([ 1., -4.,  4.]), array([ 0., -1., -3.]), array([], dtype=float64))

$$G(s)=\dfrac {s^2-4s+3}{s^3+4s^2+3s}=\dfrac {1}{s}+\dfrac {-4}{s+1}+\dfrac {4}{s+4}$$

In [12]:
signal.residue([1,3,3],[1,11,45,81,54])
#repeated pole

(array([ 1.00000000e+00+0.j, -1.00000000e+00+0.j,  1.70974346e-13-0.j,
        -3.00000000e+00+0.j]),
 array([-2.+0.j, -3.+0.j, -3.+0.j, -3.+0.j]),
 array([], dtype=float64))

$$G(s)=\dfrac {s^2+3s+3}{s^4+11s^3+45s^2+81s+54}=\dfrac {1}{s+2}+\dfrac {-1}{s+3}+\dfrac {0}{(s+3)^2}+\dfrac {-3}{(s+3)^3}$$

In [13]:
signal.residue([4,1],[1,5,17,13])
#distinct complex pole

(array([-0.3 +0.j        ,  0.15-0.71666667j,  0.15+0.71666667j]),
 array([-1.+0.j, -2.+3.j, -2.-3.j]),
 array([], dtype=float64))

$$\dfrac{4s+1}{s^3+5s^2+17s+13}=\dfrac{-0.3}{s+1}+\dfrac{0.15-0.717j}{s+2-3j}+\dfrac{0.15+0.717j}{s+2+3j}$$

In [14]:
signal.residue([1,2,12,7,6],[1,9,12,8])

(array([-0.61272259-0.05979806j, -0.61272259+0.05979806j,
        64.22544518+0.j        ]),
 array([-0.72443101+0.73119264j, -0.72443101-0.73119264j,
        -7.55113798+0.j        ]),
 array([ 1., -7.]))

$$G(s)=\dfrac {s^4+2s^3+12s^2+7s+6}{s^3+9s^2+12s+8}=\dfrac{-0.613-0.0598j}{s+0.724-0.7312j}+\dfrac{-0.613+0.0598j}{s+0.724+0.7312j}+\dfrac{64.23}{s+7.55}+s-7$$